version: '3.9'

version: '3.9'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: booking_app
    ports:
      - "3000:3000"
    env_file: 
      - ./app/.env
    depends_on:
      - db
    restart: always

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: booking_mongo
    ports:
      - "27017:27017"
    volumes:
      - ./db/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminPass
      MONGO_INITDB_DATABASE: booking
    restart: always

volumes:
  mongo_data:
